<?php

namespace thezenmonkey\foundational\Extensions;

use SilverStripe\Core\Config\Config;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\CompositeField;
use SilverStripe\Forms\NumericField;
use SilverStripe\Forms\TabSet;
use SilverStripe\Forms\Tab;

class FoundationalBaseElement extends DataExtension {
    private static $db = [
        'Small' => 'Int',
        'Medium' => 'Int',
        'Large' => 'Int',
        'XLarge' => 'Int',
        'XXLarge' => 'Int',
        'StickyProperties' => 'Varchar(255)',
        'ContainerProperties' => 'Varchar(255)',
        'ElementProperties' => 'Varchar(255)',

    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->removeByName('Small');
        $fields->removeByName('Medium');
        $fields->removeByName('Large');
        $fields->removeByName('XLarge');
        $fields->removeByName('XXLarge');

        $fields->addFieldToTab(
            'Root.Settings',
            TabSet::create(
                'ElementalOptions',
                $themeOptions = new Tab('ThemeOptions'),
                $foundationOptions = new Tab('FoundationOptions'),
                $advancedOptions = new Tab('Advanced')
            )
        );

        $cellSize = CompositeField::create();

        $cellSize->push(NumericField::create('Small', 'At Small Screen Sizes')
                                     ->setHTML5(true)
                                     ->setAttribute('max', 12));
        $cellSize->push(NumericField::create('Medium', 'At Medium Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        $cellSize->push(NumericField::create('Large', 'At Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));

        if(Config::inst()->get('BaseElement', 'UseXLarge')) {
            $cellSize->push(NumericField::create('XLarge', 'At X-Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        }

        if(Config::inst()->get('BaseElement', 'UseXXlarge')) {
            $cellSize->push(NumericField::create('XXLarge', 'At XX-Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        }
        
        $foundationOptions->push($cellSize);

        $advancedOptions->push(TextField::create('ContainerProperties',"Extra Properties for Container"));
        $advancedOptions->push(TextField::create('ElementProperties',"Extra Properties for Element"));

        if($this->owner->ClassName !== 'ElementList') {

            $fields->addFieldToTab(
                'Root.Settings.ElementalOptions.Advanced',
                TextField::create('StickyProperties')->setDescription('Please refer to <a href="https://foundation.zurb.com/sites/docs/sticky.html" target="_blank">Foundation Docs</a> for information.')
            );
        }


        $this->owner->extend('updateThemeOptions', $themeOptions);
        $this->owner->extend('updateFoundationOptions', $foundationOptions);
        $this->owner->extend('updateAdvancedOptions', $advancedOptions);

        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }


}