<?php

namespace thezenmonkey\foundational\Extensions;

use SilverStripe\Core\Config\Config;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\CompositeField;
use SilverStripe\Forms\NumericField;
use SilverStripe\Forms\TabSet;
use SilverStripe\Forms\Tab;

class FoundationalBaseElement extends DataExtension {
    private static $db = [
        'Small' => 'Varchar(255)',
        'Medium' => 'Varchar(255)',
        'Large' => 'Varchar(255)',
        'XLarge' => 'Varchar(255)',
        'XXLarge' => 'Varchar(255)',
        'StickyProperties' => 'Varchar(255)',
        'ContainerProperties' => 'Varchar(255)',
        'ElementProperties' => 'Varchar(255)',

    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->removeByName('Small');
        $fields->removeByName('Medium');
        $fields->removeByName('Large');
        $fields->removeByName('XLarge');
        $fields->removeByName('XXLarge');

        $fields->addFieldToTab(
            'Root.Settings',
            TabSet::create(
                'ElementalOptions',
                $themeOptions = new Tab('ThemeOptions'),
                $foundationOptions = new Tab('FoundationOptions'),
                $advancedOptions = new Tab('Advanced')
            )
        );

        $cellSize = CompositeField::create();

        $cellSize->push(DropdownField::create('Small', 'At Small Screen Sizes', self::getSizeArray('small'))->setEmptyString('Choose a Size'));
        $cellSize->push(DropdownField::create('Medium', 'At Medium Screen Sizes', self::getSizeArray('medium'))->setEmptyString('Choose a Size'));
        $cellSize->push(DropdownField::create('Large', 'At Large Screen Sizes', self::getSizeArray('large'))->setEmptyString('Choose a Size'));

        if(Config::inst()->get('Foundational', 'UseXLarge')) {
            $cellSize->push(DropdownField::create('XLarge', 'At X-Large Screen Sizes', self::getSizeArray('xlarge'))->setEmptyString('Choose a Size'));
        }

        if(Config::inst()->get('Foundational', 'UseXXlarge')) {
            $cellSize->push(DropdownField::create('XXLarge', 'At XX-Large Screen Sizes', self::getSizeArray('xxlarge'))->setEmptyString('Choose a Size'));
        }
        
        $foundationOptions->push($cellSize);

        $advancedOptions->push(TextField::create('ContainerProperties',"Extra Properties for Container"));
        $advancedOptions->push(TextField::create('ElementProperties',"Extra Properties for Element"));

        if($this->owner->ClassName !== 'ElementList') {

            $fields->addFieldToTab(
                'Root.Settings.ElementalOptions.Advanced',
                TextField::create('StickyProperties')->setDescription('Please refer to <a href="https://foundation.zurb.com/sites/docs/sticky.html" target="_blank">Foundation Docs</a> for information.')
            );
        }


        $this->owner->extend('updateThemeOptions', $themeOptions);
        $this->owner->extend('updateFoundationOptions', $foundationOptions);
        $this->owner->extend('updateAdvancedOptions', $advancedOptions);

        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }

    public function getSizeArray($size) {
        if($customGrid = Config::inst()->get('Foundational', 'CustomGrid')) {

            $array = $customGrid[$size];

            return $array;

        } else {

            return self::generateSizeArray($size);
        }
    }

    public function generateSizeArray($size) {
        $gridSize = Config::inst()->get('Foundational', 'GridSize');

        $sizeArray = ['auto' => 'Auto'];
        $i = 1;

        while($i <= $gridSize) {

            $sizeArray[$size.'-'.$i] = $i . (($i > 1) ? ' Units' : ' Unit');
            $i++;
        }

        return $sizeArray;
    }

    public function getHolderClasses() {

        $style = '';

        if($this->owner->ClassName !== 'DNADesign\ElementalList\Model\ElementList') {

            $style .= ' ' . Config::inst()->get('Foundational', 'CellClass');
            $style .= ' ' . (string) $this->owner->Small;
            $style .= ' ' . (string) $this->owner->Medium;
            $style .= ' ' . (string) $this->owner->Large;
            $style .= ' ' . (string) $this->owner->XLarge;
            $style .= ' ' . (string) $this->owner->XXLarge;
        }
        $style = implode( " ", $this->owner->extend('updateHolderClasses', $style) );

        return $style;
    }


    public function getThemeClasses() {
        $classes = null;

        $classes = $this->owner->extend('updateThemeClasses', $classes);

        return $classes;
    }


}