<?php
/**
 * Class: FoundationalElementList
 * Summary
 * Description
 * @author: richardrudy
 * @package thezenmonkey\founational\Extensions  * @version:
 */


namespace thezenmonkey\foundational\Extensions;

use SilverStripe\Core\Config\Config;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Tab;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Forms\CheckboxField;
use SilverStripe\Forms\CompositeField;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\NumericField;
use UncleCheese\DisplayLogic\Forms\Wrapper;

class FoundationalElementList extends DataExtension
{

    private static $db = [
        'GridDirection' => 'Varchar',
        'Full' => 'Boolean',
        'BlockGrid' => 'Boolean'

    ];

    private static $defaults = [
        'GridDirection' => 'grid-x'
    ];

    public function updateCMSFields(FieldList $fields)
    {

        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
    }

    public function updateFoundationOptions(Tab $fields) {

        $fields->removeByName('Small');
        $fields->removeByName('Medium');
        $fields->removeByName('Large');
        $fields->removeByName('XLarge');
        $fields->removeByName('XXLarge');

        $directions = $this->owner->config()->get('GridDirections');


        $fields->push(DropdownField::create('GridDirection', 'Direction', $directions));
        $fields->push(CheckboxField::create('Full', 'Full Width'));

        $fields->push(CheckboxField::create('BlockGrid')
                                   ->setDescription(
                                       'All Children Form a with defined width see 
<a href="https://foundation.zurb.com/sites/docs/xy-grid.html#block-grids" target="_blank">Foundation Docs</a> 
for details'
                                   ));

        $blockGrid = CompositeField::create();

        $blockGrid->push(NumericField::create('Width At Small Screen Sizes')
                                     ->setHTML5(true)
                                     ->setAttribute('max', 12));
        $blockGrid->push(NumericField::create('Medium', 'Width At Medium Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        $blockGrid->push(NumericField::create('Large', 'Width At Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));

        if(Config::inst()->get('BaseElement', 'UseXlarge')) {
            $blockGrid->push(NumericField::create('XLarge', 'Width At X-Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        }

        if(Config::inst()->get('BaseElement', 'UseXXlarge')) {
            $blockGrid->push(NumericField::create('XXLarge', 'Width At XX-Large Screen Sizes')->setHTML5(true)->setAttribute('max', 12));
        }

        $blockGridSizes = Wrapper::create($blockGrid);

        $blockGridSizes->displayIf('BlockGrid')->isChecked();

        $fields->push( $blockGridSizes );


    }



}